### ISSUE TITLE
Is it possible to view spotify saved albums / followed artists

### ISSUE THREAD

**Issue by alligatortower** [tkem/mopidy-mobile#118]
I organize most of my music on spotify by saving albums and following artists. Is this information retrievable via their api? I would imagine the UX being Library -> Spotify -> Saved Albumbs / Followed Artists.

This is very much a "nice to have" as I can achieve essentially the same functionality by saving albums to playlists in the meantime. Cheers.

**Comment by tkem** [comment]
Sorry, cannot say much about this since I hardly ever use Spotify. You should post this question to the Mopidy discussion group or, if you think its a bug, the mopidy-spotify issue tracker.
Mopidy-Mobile will show you everything that's available from mopidy-spotify via the browse interface.

**Comment by alligatortower** [comment]
Oh I see, thanks.

**Comment by adamcik** [comment]
libspotify doesn't have this info, so mopidy-spotify can't support it. mopidy-spotify-web might if Spotify chooses to add the needed API endpoints in the new web APIs.

**Comment by alligatortower** [comment]
@adamcik just installed and authorized mopidy-spotify-web, it's allowing me to view my saved albums and artists via this app. So, hell yeah :)
