### ISSUE TITLE
Mopidy blocks when accessing shared Windows drive via SMB mount

### ISSUE THREAD

**Issue by drasko** [tkem/mopidy-mobile#123]
I have a mounted SMB drive on a Linux host. Drive is physically on a Windows machine on the network.

I can access music via Moped, however using `mopidy-mobile` I can not access folder (mountpoint). Not only that `mopidy-mobile` does not access the folder, but it blocks whole Mopidy server. Even killing mopidy server with `CTRL + C` is not possible anymore, so maybe some additional threads have been spawned that prevent server from shutting down.

**Comment by drasko** [comment]
Hmm... I observed logs (`mopidy -v`) - it seems just that dir browsing is sooooo long, and `mopidy-mobile` "downloading" spinner indication disssapears. So that's why I thought that this are blocked - actually mopidy server was busy working. We just need to wait a lot for things to appear.

**Comment by tkem** [comment]
@drasko: thanks for pointing this out (and digging deeper so you found the reason for this yourself).
I was already thinking about adding some (configurable) timeout mechanism, so the the spinner would not just disappear, but the user would be presented with some "Timeout occurred: Wait or Reconnect?" dialog. Details TBD, but the spinner just going away while the request is still being served isn't very intuitive.

**Comment by tkem** [comment]
Will be handled in #126.
