### ISSUE TITLE
Show all track/album artists

### ISSUE THREAD

**Issue by tkem** [tkem/mopidy-mobile#124]
Currently, Mopidy-Mobile only displays the first artist for a given track or album in various places (track info, lookup, playback, search, tracklist).

Since backends may support multiple artists per track/album, all respective artist names should be shown, i.e. concatenated for display. The seperator may be a special character for easier debugging.

**Comment by F74** [comment]
With other client I can browse the Artists name ( the full list in this 
case)


or I can browse by years



But with Moped don't show the artists.


The COMPOSER works Fine.



Flavio


------ Messaggio originale ------
Da: "Thomas Kemmer" <notifications@github.com>
A: "tkem/mopidy-mobile" <mopidy-mobile@noreply.github.com>
Inviato: 22/08/2015 21:09:49
Oggetto: [mopidy-mobile] Show all track/album artists (#124)

**Comment by tkem** [comment]
Example: For `spotify:track:2bNrvWD9d5Zn9tS8XvcaMk`, only one of two artists ("Avicii" and "Nick Romero") is listed.
