### ISSUE TITLE
Only top of cover art shown on wide screens

### ISSUE THREAD

**Issue by jodal** [tkem/mopidy-mobile#131]
If using Mopidy-Mobile on a desktop or for example the Raspberry Pi 7" touch screen (800x480px) you can only see the top part of the cover art, as it scales to fill the width of the screen.

**Comment by tkem** [comment]
Same effect when rotating most phones so the UI is displayed in "landscape" mode.
Adding a bit of responsiveness to the playback screen would be nice.

**Comment by tkem** [comment]
In the end, it should look like this:
https://lh6.ggpht.com/T2n8ECMh6eigr7yBiJdnSA1xnPrMsQVj2UD5cIhHsfesvL2XjC-URIdWdhCJr2JwIPoi=h900

**Comment by tkem** [comment]
In the mean time, I'd suggest @jodal just rotates his Pi Display by 90° ;-)

**Comment by tkem** [comment]
Check out http://ionicframework.com/docs/components/#grid-vertically-align

**Comment by tkem** [comment]
Using ionic grid, this would look something like this on different devices:

![screenshot from 2015-11-05 20 32 27](https://cloud.githubusercontent.com/assets/2833077/10979373/757d5f78-83fc-11e5-9b69-7e05e4ab66d0.png)
![screenshot from 2015-11-05 20 34 28](https://cloud.githubusercontent.com/assets/2833077/10979425/b59974de-83fc-11e5-93f6-2baf961de7c7.png)
![screenshot from 2015-11-05 20 37 24](https://cloud.githubusercontent.com/assets/2833077/10979474/0c211dd4-83fd-11e5-83e7-23878a2a2fb5.png)

Except for 10" tablets and other device which have "lots of" horizontal pixels, this seems to be the way to go. Maybe wrapping should be bound to vertical and not horizontal resolution?

**Comment by tkem** [comment]
OTOH, 10" support has never been the focus of MoMo, so what the heck...

**Comment by tkem** [comment]
Using a custom media query that actually checks `orientation` and only displays columns side by side  in landscape mode would benefit smaller tablets, too.
Ionic's implementation only checks for `max-width`, so will have to copy this.

**Comment by tkem** [comment]
In landscape mode, there'd be ample space for displaying other track data, of course; but that's another issue...
