### ISSUE TITLE
Can't open web extension in browser

### ISSUE THREAD

**Issue by henne90gen** [tkem/mopidy-mobile#148]
When I try to reach Mopidy Mobile with Chrome or Firefox I get the following [screen](http://imgur.com/HhqrrTE).
I reinstalled Mobile already. Mopidy is version 1.1.1 and MopidyMobile is version 1.6.2
Connecting to the website results in this log:

INFO     2015-11-16 20:01:46,746 [7187:HttpServer] root
  304 GET /mobile/index.html (192.168.178.34) 13.66ms
DEBUG    2015-11-16 20:01:46,813 [7187:HttpServer] mopidy_mobile.web
  Get static resource for mopidy-mobile.bundle.min.js?v=1.6.2
INFO     2015-11-16 20:01:46,827 [7187:HttpServer] root
  304 GET /mobile/mopidy-mobile.bundle.min.js?v=1.6.2 (192.168.178.34) 17.71ms
DEBUG    2015-11-16 20:01:46,838 [7187:HttpServer] mopidy_mobile.web
  Get static resource for css/ionic-light.min.css?v=1.6.2
INFO     2015-11-16 20:01:46,851 [7187:HttpServer] root
  304 GET /mobile/css/ionic-light.min.css?v=1.6.2 (192.168.178.34) 15.75ms

**Comment by tkem** [comment]
In this case, something has terribly gone wrong (I guess you already thought so) ;-)
Try closing and re-opening the browser, clear the cache, try Ctrl-R for "real" browser reload (a couple of times).
If that doesn't help, please reinstall Mopidy-Mobile.

**Comment by tkem** [comment]
Please also have a look at the browser console (Ctrl-Shift-I in both Chrome and Firefox) and look for anything suspicious.

**Comment by henne90gen** [comment]
I restarted the Pi, with no change in situation.
Here is the full [server log](http://pastebin.com/ksKC5Gnv) after I tried connecting to the web interface once.

**Comment by tkem** [comment]
Have you tried scrapping your local config and running with default settings?

**Comment by tkem** [comment]
Can we close this?

**Comment by henne90gen** [comment]
I found out what the reason for this error was. I was running a very old version of mopidy and didn't realize that. I recently reinstalled mopidy, since then everything works like a charm. Thanks for your help and keep up the good work.
