### ISSUE TITLE
Error playing Youtube search results

### ISSUE THREAD

**Issue by jcass77** [tkem/mopidy-mobile#149]
The results returned when searching Youtube will not play on my setup.

The error in the log file is:

Need 11 character video id or the URL of the video. Got //youtube:video/PSY - GANGNAM STYLE() MV.9bZkp7q19f0

This works in the Mopidy-HTTP-Kuechenradio (0.4.2)?

Mopidy (1.1.1), Mopidy-Youtube (2.0.1), pafy (0.4.2), Mopidy-MusicBox-Webclient (2.0.0)

**Comment by tkem** [comment]
Never tried the youtube extension before, so great excuse to play around with it ;-)
 It looks like `youtube` URIs are not properly escaped, for example `youtube:video/PSY - GANGNAM STYLE() MV.9bZkp7q19f0`. I suggest you file a bug with mopidy-youtube.

**Comment by tkem** [comment]
Apart from that, the URI passed to `tracklist.add` seems to be the same (unencoded) as returned by the mopidy-youtube extension, so I have no clue what's wrong here:
```
DEBUG    2015-11-28 11:28:37,782 [30901:HttpServer] mopidy.http.handlers
  Received WebSocket message from 127.0.0.1: u'{"method":"core.tracklist.add","params":{"uri":"youtube:video/PSY Gangnam Style Official Video.GyT_KyAqDEc"},"jsonrpc":"2.0","id":43}'
INFO     2015-11-28 11:28:37,783 [30901:YouTubeBackend-12] mopidy_youtube
  Need 11 character video id or the URL of the video. Got //youtube:video/PSY Gangnam Style Official Video.GyT_KyAqDEc
DEBUG    2015-11-28 11:28:37,900 [30901:HttpServer] mopidy.http.handlers
```

**Comment by tkem** [comment]
I also get the same error/info in the log when using ncmpcpp, which reports "No such song".
I also tried updating `pafy` as recommended in the mopidy-youtube README:
```
Mopidy-Youtube==2.0.1
pafy==0.4.2
```
Please note that "Show track info..." in the track context menu seems to work, which uses the same URI. It only seems to be a problem when trying to add a track to the tracklist.
Closing this, since it does not seem to be Mopidy-Mobile related.

**Comment by jcass77** [comment]
Yes don't believe this is related to Mopidy-Mobile in the end. I've submitted a PR to the Mopidy-Youtube project that should fix this: https://github.com/mopidy/mopidy-youtube/pull/50

**Comment by tkem** [comment]
Great, thanks! Looking forward to having mopidy-youtube on my kitchen radio - the girls will love it ;-)
