### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by miclill** [tkem/mopidy-mobile#166]
Just discovered this awesome app. Would be nice to see this on F-Droid.
Cheers

**Comment by tkem** [comment]
The last time I looked into F-Droid, it did not support submitting Cordova apps directly. Unless this has changed recently, I don't think it's worth the effort.

**Comment by miclill** [comment]
Hmm, bummer. Thanks anyway for the consideration.

**Comment by Poussinou** [comment]
@tkem We now support Cordova apps! Can you reopen this Issue?

Maybe @Rudloff could have a look at this :)

**Comment by Rudloff** [comment]
We do support Cordova apps but in order for us to easily build them, we require the Android project (usually `platforms/android/`) to be published in the Git repository. (Because our build server uses Gradle and does not have the Cordova CLI tool.)

**Comment by licaon-kter** [comment]
Any news?

**Comment by tkem** [comment]
...would have been posted here.

**Comment by IzzySoft** [comment]
@tkem so could you add the project files @Rudloff mentioned to your repository, so we can build the app?

**Comment by tkem** [comment]
No. These are generated files and don't belong in the source repository.

**Comment by IzzySoft** [comment]
OK, thanks. Then we cannot build your app and I'll have to close that request on our end. Would you not even consider including them via a git submodule? Then they wouldn't be directly in your source repo, but still available for us to build the app.

**Comment by tkem** [comment]
@IzzySoft: You mean, would I create and _maintain_ an addition repo/branch/whatever to compensate for the shortcomings (not being able to deal with Cordova apps - have a look at the `.travis.yml` file how this is done) of a service I don't use and have very little to no interest in?
Case closed.
