### ISSUE TITLE
Progress bar only updated once a second

### ISSUE THREAD

**Issue by adamcik** [tkem/mopidy-mobile#167]
Playing short song, say 10 seconds the progress bar updates end up being very jerky as it only gets updated once a second. Using `requestAnimationFrame` you could probably update more often while still being battery friendly, and possibly only triggering a redraw if the location moves at least n-pixels.

I also happen to have http://adamcik.github.io/media-progress-timer/ which wraps a lot of this logic up in a helper intended for mopidy clients and anything else that needs to track time.

**Comment by tkem** [comment]
I appreciate the feedback, and of course I know about `media-progress-timer` ;-)
Even though I agree the current progress handling could/should be improved somewhat, everything that primarily concerns "10 second songs" won't make it to the top of my priority list for (at least) the next six months or so...
Patches welcome, of course ;-)

**Comment by tkem** [comment]
https://github.com/tkem/mopidy-mobile/blob/3537429d13ee00f0cc4eb53f4bc93dc2fe1b0fa9/www/app/playback/playback.js#L20

**Comment by adamcik** [comment]
10s songs is a rather strange corner case, I would never have noticed if I wasn't hunting down short tracks to speedup testing of a mopidy-spotify issue :-) And indeed I can see how this could just be closed as won't fix and then just leave it until you get around to your TODO in the code.

**Comment by tkem** [comment]
Leaving it open as a reminder. Needs a refactoring badly, anyway.

**Comment by tkem** [comment]
This will probaböy never happen...
