### ISSUE TITLE
Preload icomoon font

### ISSUE THREAD

**Issue by tkem** [tkem/mopidy-mobile#170]
The icomoon font only gets loaded when"Pacman" is first added to the DOM, resulting in noticeable "flicker". Lookin for a pure CSS solution hinted at using `:after` or `:before` with invisible content and font face set accordingly.

**Comment by tkem** [comment]
Additionally, the icomoon `@import` should be moved out of `_styles.scss`, to make stylesheets more modular.

**Comment by HenryLiuPI** [comment]
Hi, did you figure out how to preload ico-moon font?
