### ISSUE TITLE
Show track uri when no metadata present

### ISSUE THREAD

**Issue by vor0nwe** [tkem/mopidy-mobile#175]
Currently, when Mopidy is playing a track that doesn't have any metadata associated with it (which unfortunately still happens regularly in my collection), I get to see "nothing playing", even when there's definitely something playing.
Would it be possible to show *something*, like the uri? That might contain at least some clue as to what's playing: in the case of a local file certainly...

**Comment by tkem** [comment]
Sure. I *thought* that's already exactly what's happening, but code proves you're right and I was wrong ;-)
Will be fixed in the next bugfix release. Thanks for reporting!
