### ISSUE TITLE
Search always returning empty results

### ISSUE THREAD

**Issue by colinnuk** [tkem/mopidy-mobile#176]
I recently updated to 1.6.8 and search seems to not work at all any more, as in it just displays an empty list. It's working for other GUIs. Is it still working for you or is my installation broken in some way?

**Comment by tkem** [comment]
When you say "search seems to not work", could you please be a little more specific?
For example, the "Search here " option in the library root or in a specific extensions subdirectory, the "advanced" search accessible via the search icon with search fields set to "any" or "artist", or...

**Comment by tkem** [comment]
And yes, it's working for me, but my setup is probably quite different from yours (no Spotify here, for example), so more details would be welcome ;-)

**Comment by tkem** [comment]
Any updates on this, or can this issue be closed?

**Comment by colinnuk** [comment]
Ah sorry, hadn't checked this for a while and thought I had github notifications turned on.

It seems like it is actually a backend issue in Mopidy - I had tested this last week and it worked on MusicBox but not Mopidy-Mobile (hence opening this issue), but on looking at the logs it's now throwing errors all over the place :( .
