### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by slimer** [tkem/mopidy-mobile#179]
Hi,
Here is my first version of the spanish translation (I can translate it to catalan, too). Can you put it into the code?

I can't upload .js files so I put a fake .txt extension in it.

[es.js.txt](https://github.com/tkem/mopidy-mobile/files/151385/es.js.txt)

**Comment by tkem** [comment]
Thank you very much! I was hoping for more translations from users all the time! Sure this will go into the next release.

**Comment by tkem** [comment]
As a translator, you should also be mentioned on the "About"/" Acerca de" page, of course. So please let me know if I should use your real name and/or email address.

**Comment by slimer** [comment]
You can put my nickname, slimer. I can send you tomorrows the catalan translation. I life in Andorra, a little country between Spain and France, with this as official language and the most understanded. there's 7.000.000 people who understand it in Catalonia, Valencia and balearian island. Can you put it on the new version?
Thanks to you for a very goog job!

**Comment by slimer** [comment]
You can put my nickname, slimer. I can send you tomorrows the catalan translation. I life in Andorra, a little country between Spain and France, with this as official language and the most understanded. there's 7.000.000 people who understand it in Catalonia, Valencia and balearian island. Can you put it on the new version?
Thanks to you for a very good job!

**Comment by tkem** [comment]
Sure, Catalan would be welcome, too!

**Comment by tkem** [comment]
For the "About" page, I will also need translations for "Translations:". Google says "Traducciones" for Español and "Traduccions" for Català. Is this correct?

**Comment by tkem** [comment]
Will look like this: "Translations: slimer (Español, Català), ...

**Comment by slimer** [comment]
Yes, it's correct.  Thank you again. You've do all the work, we only try to
make it accessible to more people.
El dia 29/02/2016 22:23, "Thomas Kemmer" <notifications@github.com> va
escriure:

**Comment by tkem** [comment]
No, thank you! I only have statistics for the Android app from Google Play Store, and that shows that ca. 20% of users are from Germany and less than 3% are from Spain. I guess the German translation has something to do with that. I'm curious how adding Spanish and Catalan locales will affect that.

**Comment by slimer** [comment]
Hi!

Here are the promised translations. I've made some corrections on the spanish (I misunderstood No servers with number of servers and some accents lost).
[ca.js.txt](https://github.com/tkem/mopidy-mobile/files/152411/ca.js.txt)
[es.js.txt](https://github.com/tkem/mopidy-mobile/files/152412/es.js.txt)

**Comment by tkem** [comment]
Thanks. I did a quick check with Google Translate, and I just want to make sure this is right:
```
'Cover art': 'Portada',
'Edit tracklist': 'Editar lsita de pistas',
```
Google says "Portada" means "Home", and I'm not sure this is a good name for the screen where you configure Cover Art providers (Last.fm, Coverart Archive, etc.). 

"lsita" is probably just a typo ;-)

**Comment by slimer** [comment]
Portada also means the cover art of a LP, newspaper, book, etc. Maybe
Carátula (Carátulas as plural) will be more specific and avoid confusión
for Home. In catalan caràtula (just change the accent direction).
Yes, you're right lsita is a typo, sorry :-(

2016-03-01 10:09 GMT+01:00 Thomas Kemmer <notifications@github.com>:

> Thanks. I did a quick check with Google Translate, and I just want to make
> sure this is right:
>
> 'Cover art': 'Portada',
> 'Edit tracklist': 'Editar lsita de pistas',
>
> Google says "Portada" means "Home", and I'm not sure this is a good name
> for the screen where you configure Cover Art providers (Last.fm, Coverart
> Archive, etc.).
>
> "lsita" is probably just a typo ;-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tkem/mopidy-mobile/issues/179#issuecomment-190624861>.
>



-- 
Enviat des de el meu microones

**Comment by tkem** [comment]
Thank you! Just wanted to make sure there was no misunderstanding. And I also have to make sure you do not hide any dirty jokes in the texts ;-)

**Comment by slimer** [comment]
Not dirty jokes, only dirty mistakes ;-)

2016-03-01 10:32 GMT+01:00 Thomas Kemmer <notifications@github.com>:

> Thank you! Just wanted to make sure there was no misunderstanding. And I
> also have to make sure you do not hide any dirty jokes in the texts ;-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tkem/mopidy-mobile/issues/179#issuecomment-190632707>.
>



-- 
Enviat des de el meu microones
