### ISSUE TITLE
Limit number of URIs per get_images() request

### ISSUE THREAD

**Issue by tkem** [tkem/mopidy-mobile#183]
This may be an issue with back ends that don't implement `get_images()` but rely on the default implementation that uses `lookup()`. Mopidy-Tidal seems to be especially affected by this, according to @ZenithDK: see also #126.

**Comment by tkem** [comment]
In addition to requesting images in smaller batch sizes, it would be nice to be able to "cancel" image retrieval, e.g. on `$ionicView.leave`. Image retrieval may then be moved to `$ionicView.enter` (confirm that's fired after resolves), and may check against the current controller's local `images`.

**Comment by tkem** [comment]
@ZenithDK: When you settled in, it would be nice if you would give MoMo v1.6.11 a try with mopidy-tidal. You'll still see a lot of `lookup`s, but server responsibility and general usability should be much improved (hopefully).

**Comment by ZenithDK** [comment]
Just tried this out (I'm off sick today, man flu 😑) and it works tons
better. Thanks a lot!
