### ISSUE TITLE
All playlist to the tracklist in just one click

### ISSUE THREAD

**Issue by slimer** [tkem/mopidy-mobile#189]
It's posible to add a feature to add all playlists to the tracklist?

Thanks in advance.

**Comment by tkem** [comment]
You can add all tracks from a single playlist to the tracklist using the menu or "play" button.
Adding *all* tracks from *all* playlists doesn't really make sense, IMHO.

**Comment by slimer** [comment]
Yes, it can sound nonsense but I work for a store with a large collection
of playlists sound all in random mode (aprox. 60 playlists and growing) and
when the server restarts (Probably in Sunday, as Murphy can predict) They
or I spent so many time putting again all tracks of all playlist again in
the tracklist. May be an option to remember the last tracklist or to save
it?

2016-03-15 10:41 GMT+01:00 Thomas Kemmer <notifications@github.com>:

> You can add all tracks from a single playlist to the tracklist using the
> menu or "play" button.
> Adding *all* tracks from *all* playlists doesn't really make sense, IMHO.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/tkem/mopidy-mobile/issues/189#issuecomment-196743114
>



-- 
Enviat des de el meu microones

**Comment by tkem** [comment]
AFAIK, work for saving/restoring Mopidy state including tracklist is already in progress: https://github.com/mopidy/mopidy/pull/1376. As a workaround, I think writing a small shell script that uses `mpc` for adding the tracklists at startup time would make more sense than adding this to Mopidy Mobile. So closing this, but thanks for the input.
