### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by tkem** [tkem/mopidy-mobile#192]
The following user interface strings (with default translations) will be added in v1.7.0:

- [x] ConnectionError: 'Connection error' (Mopidy `Error.name`)
- [x] Error: 'Error'
- [x] Request timeout: 'Request timeout' (UI setting label)
- [x] ServerError: 'Server error' (Mopidy `Error.name`)
- [x] TimeoutError: 'Timeout error' (Mopidy `Error.name`)
- [x] {count} seconds: '{{count}} seconds' (UI setting values)
- [x] {count} tracks: {count, plural, =0{No tracks} one{1 track} other{# tracks}} (Tracklist title)

**Comment by tkem** [comment]
@slimer: If you find the time, it would be great if you could provide Spansih and Catalan translations for these.

**Comment by slimer** [comment]
Spanish:

 ConnectionError: 'Connection error' (Mopidy Error.name) -> Error de conexión
 Error: 'Error' -> "Error"
 Request timeout: 'Request timeout' (UI setting label) -> "Tiempo de espera de la consulta agotado."
 ServerError: 'Server error' (Mopidy Error.name) -> "Error del servidor"
 TimeoutError: 'Timeout error' (Mopidy Error.name) -> "Error de tiempo de espera agotado"
 {count} seconds: '{{count}} seconds' (UI setting values) -> "{{count}} segundos"

Catalan:

 ConnectionError: 'Connection error' (Mopidy Error.name) -> "Error de connexió"
 Error: 'Error' -> "Error"
 Request timeout: 'Request timeout' (UI setting label) -> "Temps d'espera de la consulta esgotat"
 ServerError: 'Server error' (Mopidy Error.name) -> "Error del servidor"
 TimeoutError: 'Timeout error' (Mopidy Error.name) -> "Error de temps d'espera esgotat"
 {count} seconds: '{{count}} seconds' (UI setting values) -> "{{count}} segons"

**Comment by tkem** [comment]
Thank you! But is it possible to find something shorter for "Request timeout"? This will be used as labels on the Look and Feel settings and might be cut off on smaller phones...

**Comment by tkem** [comment]
Also translations for "Timeout error" are a little long. In German, I just use a translation for "Timeout", if that helps.

**Comment by tkem** [comment]
Maybe just "Tiempo de espera" is good enough? Or does that sound too ridiculous?

**Comment by tkem** [comment]
@slimer: I'm also going to switch to
messageformat (https://github.com/SlexAxton/messageformat.js) since that makes pluralization etc. much easier.
Therefore I'll also change the title of an empty tracklist to "No tracks" or "Zero tracks", so I'd also need translations for that...

**Comment by slimer** [comment]
May be Timeout can be translated as "Tiempo agotado", removing "de espera" is legible too.
"Request Timeout" => "Tiempo de consulta agotado".
"Timeout Error" -> "Error de tiempo agotado"
In catalan replace "Tiempo" for "Temps" and "agotado" for "esgotat".

"No tracks" -> No hay Pistas/ Sin Pistas (shorter and legible, too) Track-> pista Tracks->pistas
"Zero tracks" -> Cero Pistas

**Comment by tkem** [comment]
Great, thanks!

**Comment by tkem** [comment]
@slimer: Thanks, I think that's all that will be needed for Mopidy Mobile v1.7.0 (after moving some open issues to v1.8.0) ;-)

If you find the time, you are welcome to have a final look at https://github.com/tkem/mopidy-mobile/tree/dev/1.7.0/www/app/locale; I'm not sure I did everything right, and I have some doubts about capitalization (Pistas/pistas and Pistes/pistes).

**Comment by slimer** [comment]
Catalan: 
 'Request timeout': 'Temp de consulta esgotat' - 'Temps de consulta esgotat'

Spanish:

All correct.

**Comment by tkem** [comment]
Gracias/gràcies!
