### ISSUE TITLE
Webinterface: Spacebar should start playback

### ISSUE THREAD

**Issue by henne90gen** [tkem/mopidy-mobile#207]
It would be nice if pressing the space bar could start playback in the web interface, similar to YouTube where one can start playing a video by pressing the space bar.
Just tried it again, functionality is there, but only works when the current playback is paused, not if it was stopped.

**Comment by tkem** [comment]
There's usually no "spacebar" on mobile devices, so there won't be special support for this or other keyboard shortcuts.
