### ISSUE TITLE
Add folder to Queue

### ISSUE THREAD

**Issue by JavaJens** [tkem/mopidy-mobile#209]
I'd like to be able to add entries recursively to the queue.
For example, when browsing an artist, I want to add all songs by that artist.

I think none of the existing mopidy clients can do this and it would be awesome if mopidy-mobile could be the first ;)

**Comment by tkem** [comment]
Well, I think there are some good reasons this isn't supported by any client...
Recursively retrieving tracks from any directory may potentially take *very* long, and require *lots* of requests. So you'd eventually have to decide on a timeout/max. limit when to abort these. Also some backends may have loops in their directory structure, so you'd have to guard against those, too. So at least for now, I'd rather not add any "recursive" features.

**Comment by adamcik** [comment]
From mopidy's / backend's point of views it would make more sense if you add an URI that represents an artist and the backend expands it to tracks to add. The mopidy APIs should already support this. So it's mostly up adding support for adding the current URI in browse to the tracklist. Catch is I'm unsure about what backends if any will do the right thing for this case. But this is at least how I think it should be done from an API point of view.

**Comment by tkem** [comment]
Lack of, or let's say "varying levels of support of" `library.lookup(artist-or-album-uri)` by backends are basically the reason MoMo doesn't use this (yet).

**Comment by JavaJens** [comment]
Ok, thanks for the info. Maybe if the backend implementations become more stable you can reopen this. I would really appreciate it.

For others: in the meantime I use MPDroid whenever I want to add more songs at once.

**Comment by tkem** [comment]
Reopening this, since that's something I definitely want to look into for MoMo v2.0, for purely selfish reasons ;-)
