### ISSUE TITLE
Review v1.8.0 translations

### ISSUE THREAD

**Issue by tkem** [tkem/mopidy-mobile#212]
Several locale-dependent strings were added in the [dev/1.8.0](https://github.com/tkem/mopidy-mobile/tree/dev/1.8.0/www/app/locale) branch:
```
Share
Volume keys
```
@slimer: Initial translations for `es` and `ca` were added using Google Translate, but maybe you should have a look, if you're still interested...

**Comment by tkem** [comment]
@slimer: are you still there?

**Comment by slimer** [comment]
Yes, sorry. I'm a little busy. As soon as I have time I'll check the
translations.

El dia 21 febr. 2017 08:16, "Thomas Kemmer" <notifications@github.com> va
escriure:

**Comment by tkem** [comment]
Thank you!
