### ISSUE TITLE
Random playing of single playlist

### ISSUE THREAD

**Issue by realjax** [tkem/mopidy-mobile#219]
I'm pretty sure I used to be able to play random tracks from  a single playlist. But when I select a playlist and enable random play, it plays songs from all playlists now..

**Comment by tkem** [comment]
Sorry, but by the *very* little information given here, I can neither reproduce this, nor do I think this is really a client error. Mopidy Mobile can just load playlists into the current tracklist, and/or enable/disable random mode in Mopidy itself. It doesn't do any "randomization" by itself, nor can it play tracks that aren't already in Mopidy's tracklist. Are you sure, it's not *you* doing something wrong here (in which case it would be more appropriate to post this to https://discuss.mopidy.com)?
