### ISSUE TITLE
Not all cover arts are displayed correctly

### ISSUE THREAD

**Issue by LeoCal** [tkem/mopidy-mobile#221]
Hi,

I'm running the latest version of Mopidy-Mobile (1.8.3) and I see an issue with rendering the cover arts embedded as metadata in my local MP3s.

In particular, on my own Mac, I see iTunes showing all of them correctly; however, after copying the same MP3s to my NAS, I see only half of them displayed correctly by Mopidy-Mobile.

Is it a known issue?

Thanks,
Leo

**Comment by tkem** [comment]
What local backend are you using? Do you have mopidy-local-images installed and set up correctly? Do you have any external cover art providers enabled (lastfm, for example)?

**Comment by LeoCal** [comment]
Hi,

yes I have also tried installing mopidy-local-image but that didn't help.

And yes, I have enabled external cover art providers (all 3 available actually) but only some of the are being downloaded. I guess the MP3 metadata are not matching 1:1 the corresponding online metadata therefore they could not be resolved successfully.

Thanks
Leo

**Comment by LeoCal** [comment]
Thanks for your reply, I'll give it another try when I come back home and will let you know how it goes

**Comment by LeoCal** [comment]
Hi @tkem 

I've tried again a "mobile -v local scan" and I see only one image recognized out of ~300 songs by mopidy-local-images, for which I see the following info debug message:

INFO     2018-03-15 08:28:14,608 [10693:MainThread] mopidy_local_images.library
  Creating file /home/pi/.local/share/mopidy/local-images/86a95822020f223b2b5b1cdf01344fa8-420x420.jpeg 

Maybe this might actually be a problem with mopidy-local-images recognizing the cover art inside my MP3s? (encoded with a Macbook Pro)
If so I can try and contact the developer of that lib extension.

Thanks,
Leo

**Comment by tkem** [comment]
Probably. But please first try posting this on https://discourse.mopidy.com/, unless it's been verified this is actually an issue with mopidy-local-images, and not just some configuration error or whatever.

**Comment by LeoCal** [comment]
Sure, will do, thanks!
