### ISSUE TITLE
Search filtering for albums/individual songs

### ISSUE THREAD

**Issue by tehkillerbee** [tkem/mopidy-mobile#224]
As you suggested on google play store, here is my issue, although I am not sure if is a limitation of mopidy itself. When I search for an artist in my "Tidal-Artists" folder structure, I get a list of search results containing matching artists (eg. Foo Fighters). If I click the artist, I get a mixed list of songs from many different albums in a random order but no albums appear in the list, only individual songs. If I repeat this search on the mopidy web interface, I get an almost identical list of tracks. However, I also get a list of albums for the artist that I selected (see below screenshot)
![image](https://user-images.githubusercontent.com/815886/42781012-382a1746-8945-11e8-8392-f9d0d7b9b3eb.png)

In mopidy mobile, would it be possible to filter or select between either individual tracks or albums for a specific artist and/or display them separately, similar to how it is currently done on the web interface? That  would make it easier to select and enqueue whole albums at once. 

I noticed that mopidy mobile already displays individual albums that matches the search term I have used (Left screenshot), but as soon as I select the artist, the albums disappear from the list and I get all individual songs and no albums (Right screenshot). I have tried to illustrate this as good as I can, in the below screenshots:
![image](https://user-images.githubusercontent.com/815886/42781389-4d747636-8946-11e8-8521-1c1374e38131.png)

**Comment by tkem** [comment]
So in your last pair of screenshots, you clicked the Foo Fighters artist item on top?
And you would expect (somewhat rightfully)  albums of that artist to be listed on the screen to the right, do I understand correctly?

**Comment by tehkillerbee** [comment]
Exactly; I would expect a list of albums (and/or individual tracks, depending on the filter selection) corresponding to the artist that I selected. Instead I get a list of individual tracks for the artist.

**Comment by tkem** [comment]
Ok, I'll have to look into that - it's been a while...

**Comment by tkem** [comment]
The Mopidy API that I'm using to look up artist or album URIs in that view only returns tracks: https://docs.mopidy.com/en/latest/api/core/#mopidy.core.LibraryController.lookup
I vaguely remember discussing this years ago, but I'm afraid you'll have to wait for Mopidy 3.0 or whatever.
