### ISSUE TITLE
Group artist's tracks by album

### ISSUE THREAD

**Issue by djmattyg007** [tkem/mopidy-mobile#238]
If I perform a spotify search for an artist, and select that artist in the search results, the screen I'm taken to is a (usually very long) list of every single song by that artist. It would be much friendlier if this list was grouped by album. Ideally it would follow the same interface you find when selecting an artist through the "Top Artists" mean provided through the spotify integration.

**Comment by tkem** [comment]
Mopidy Mobile does not perform any sorting or grouping of search results by itself. It displays results as delivered by Mopidy server, or in your case, the mopidy-spotify extension.
