### ISSUE TITLE
Add "advanced search" option

### ISSUE THREAD

**Issue by tkem** [tkem/mopidy-mobile#30]
Invoked from library menu. View/popup should allow to add multiple field/value entries, with fields from select box (name, album, artist, etc.).

**Comment by TheCrow1213** [comment]
+1

**Comment by maydaytx** [comment]
+1 It's especially difficult to find a self-titled album with the current search function.

**Comment by tkem** [comment]
Any suggestions for the UI are welcome!

**Comment by tkem** [comment]
- add search button to library nav-bar
- on click, open new view for composing the query
- query view displays list of key/value fields
- key is select box with translated query keys (track_name, artist, etc.)
- value is text field
- new fields can be added ("+" button)
- fields can be removed ("-" button)
- same key can be used multiple times
- on submit, query will be sent and results displayed as with current "Search here"
- note that query view is inserted into history stack, so going back will take you to query view

**Comment by TheCrow1213** [comment]
@tkem Very cool! Thanks for this :)

**Comment by tkem** [comment]
Thank you!
